sound/misc/ow.wav
sound/misc/awwcrap2.wav
sound/misc/awwman.wav
sound/misc/bud.wav
sound/misc/comeagain.wav
sound/misc/doh.wav
sound/misc/doh2.wav
sound/misc/doh3.wav
sound/misc/doh4.wav
sound/misc/doh5.wav
sound/misc/doh7.wav
sound/misc/dohnuts.wav
sound/misc/dohoo.wav
sound/misc/doomed.wav
sound/misc/er.wav
sound/misc/haha.wav
sound/misc/awwcrap.wav
sound/misc/weis.wav
sound/misc/woohoo.wav
sound/misc/woohoo2.wav
sound/misc/doit.wav
maps/aim_map_usp.res