maps/de_forge.txt
maps/de_forge.res
models/de_forge/forge_fern1.mdl
models/de_forge/forge_tree1.mdl
models/de_forge/forge_tree2.mdl
models/de_forge/forge_tree3.mdl
models/de_forge/forge_truck.mdl
overviews/de_forge.txt
overviews/de_forge.bmp
