maps/de_mon.res
maps/de_mon.txt
gfx/env/mon_sky_bk.tga
gfx/env/mon_sky_dn.tga
gfx/env/mon_sky_ft.tga
gfx/env/mon_sky_lf.tga
gfx/env/mon_sky_rt.tga
gfx/env/mon_sky_up.tga
models/mon_fakew.mdl
models/mon_veg1.mdl
models/mon_veg2.mdl
models/mon_veg3.mdl
models/mon_farol.mdl
models/mon_ponte.mdl
models/mon_estrutura.mdl
models/doenerking/e4g1e_bobby.mdl
models/doenerking/e4g1e_merc.mdl
models/doenerking/e4g1e_moskvich2141.mdl
models/doenerking/Xen_barrel3_1.mdl
models/doenerking/Xen_barrel4_2.mdl
models/doenerking/Xen_bush_big.mdl
models/doenerking/Xen_tree4.mdl
models/doenerking/Xen_tree4_3.mdl
models/doenerking/Xen_tree6.mdl
models/doenerking/Xen_tree6_3.mdl
sound/flmgrexp.wav
sprites/atm_effect.spr
sprites/sp_agua.spr
sprites/sp_agua_h.spr
de_mon.wad