maps/de_russka.txt
maps/de_russka.res
models/de_russka/russka_tree_noleaves.mdl 
gfx/env/snowup.tga
gfx/env/snowlf.tga
gfx/env/snowrt.tga
gfx/env/snowdn.tga
gfx/env/snowbk.tga
gfx/env/snowft.tga
overviews/de_russka.txt
overviews/de_russka.bmp
