sound/misc/fightclubrules.wav
sound/misc/woohoo.wav
sound/misc/woohoo2.wav
sound/misc/awwcrap.wav
sound/misc/awwcrap2.wav
sound/misc/awwman.wav
sound/misc/comeagain.wav
sound/misc/doh.wav
sound/misc/doh2.wav
sound/misc/doh3.wav
sound/misc/doh5.wav
sound/misc/doh7.wav
sound/misc/dohoo.wav
sound/misc/bud.wav
sound/misc/weis.wav
sound/misc/er.wav
sound/misc/ow.wav
sound/misc/doomed.wav
sound/misc/kenny1.wav
sound/misc/cracker1.wav
sound/misc/shot1.wav
sound/misc/nam1.wav
sound/misc/kickass1.wav
sound/misc/awwcrap32.wav
sound/misc/gotahurt.wav
sound/misc/revenge1.wav
sound/misc/bullcrap.wav
sound/misc/bullseye2.wav
sound/misc/darth.wav
sound/misc/bye.wav
sound/misc/armag02.wav
sound/misc/link2.wav
sound/misc/erotic.wav
sound/misc/outofhere.wav
sound/misc/shutup.wav
sound/misc/shutup2.wav
sound/misc/coupbucks.wav
sound/misc/awwcrap32.wav
sound/misc/dohnuts.wav
sound/misc/yipikiya.wav
sound/misc/surgepower.wav
sound/misc/whykillme.wav
sound/misc/kidbosoms.wav
sound/misc/presgay.wav
sound/misc/tuchbutt.wav
sound/misc/flaming.wav
sound/misc/choirboy.wav
sound/misc/PutdownIdiotic.wav
maps/fy_iceworld.res
de_vegas.wad
