sound/misc/multikill.wav
sound/misc/ultrakill.wav
sound/misc/killingspree.wav
sound/misc/numnuts.wav
sound/misc/failure.wav 
sound/misc/dominating.wav   
sound/misc/doublekill.wav  
sound/misc/firstblood.wav  
sound/misc/godlike.wav  
sound/misc/headshot.wav  
sound/misc/humiliation.wav  
sound/misc/killChicken.wav  
sound/misc/monsterkill.wav  
sound/misc/perfect.wav  
sound/misc/plane_drone.wav  
sound/misc/prepare.wav  
sound/misc/rampage.wav  
sound/misc/sheep.wav  
sound/misc/talk.wav 
maps/scoutzknivez.res